### PR TITLE
option_sound: fix rapid sound effect if input held down

### LINKED ISSUE #467: Glitchy sound in volume settings
https://user-images.githubusercontent.com/4934209/157334802-04ff5d66-b2e9-4fd8-812b-214c11f58eab.mp4

Small thing: when you hold right when the volume is already maxed, it will spam the adjustment SFX. This could be changed so that once maxed or muted, you can't hit right of left anymore. A bit in line with the visual arrow indicators @walkawayy was working on recently.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #467.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes

#### Descripton
Fixed sound effects playing rapidly in sound menu if input held down.
...

### CODE REVIEW

File: src/game/option_sound.c [hunk 1]
```diff
@@ -106,13 +108,10 @@ void Option_Sound(INVENTORY_ITEM *inv_item)
...
             sprintf(buf, "| %2d", g_Config.music_volume);
-            Text_ChangeText(m_Text[TEXT_MUSIC_VOLUME], buf);
-            Settings_Write();
-        }
-
-        if (g_Input.left || g_Input.right) {
             Music_SetVolume(g_Config.music_volume);
             Sound_Effect(SFX_MENU_PASSPORT, NULL, SPM_ALWAYS);
+            Text_ChangeText(m_Text[TEXT_MUSIC_VOLUME], buf);
+            Settings_Write();
```
Comment (rr-) [inline src/game/option_sound.c:114]: Can we move sprintf lower to mirror the case above?

**Review by rr- — APPROVED** [review]
