### PR TITLE
lava: fix lava trap not setting Lara on fire

### LINKED ISSUE #353: Bug: Lava trap does not kill Lara
In the corridor with the unreachable medi packs, after pulling switch, the lava does not kill Lara and instead pushes her away.

20220118_150412_Atlantis

I have to say I like this bug ;)

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #353.

### CODE REVIEW

File: src/game/traps/lava.c [hunk 1]
```diff
@@ -76,8 +76,23 @@ void LavaBurn(ITEM_INFO *item)
 
     if (!on_lava) {
         return;
+    } else {
+        LavaBurn(item);
+    }
```
Comment (rr-) [inline src/game/traps/lava.c:81]: Please change the signature of this function to return a `bool`. We have too many `Test` functions that produce unexpected side effects.

**Review by rr- — CHANGES_REQUESTED** [review]
Thanks for looking into this.

File: src/game/traps/lava.c [hunk 2]
```diff
@@ -75,9 +75,25 @@ void LavaBurn(ITEM_INFO *item)
     } while (!(type & END_BIT));
 
     if (!on_lava) {
+        return false;
+    } else {
+        LavaBurn(item);
+        return true;
```
Comment (rr-) [inline src/game/traps/lava.c:81]: This still produces side effects.

What I meant is doing this:

```diff
-TestLavaFloor(g_LaraItem);
+if (TestLavaFloor(g_LaraItem) {
+    LavaBurn(g_LaraItem);
+}
```

**Review by rr- — CHANGES_REQUESTED** [review]

File: src/game/traps/lava.c (hunk 2 above)
Comment (walkawayy) [reply src/game/traps/lava.c:81]: Ah gotcha.

File: src/game/traps/lava.c [hunk 3]
```diff
@@ -75,9 +75,24 @@ void LavaBurn(ITEM_INFO *item)
     } while (!(type & END_BIT));
 
     if (!on_lava) {
+        return false;
+    } else {
+        return true;
+    }
+}
```
Comment (rr-) [inline src/game/traps/lava.c:82]: Please make this function exit early. In other words refactor it to `return true` as soon as possible within its main loop, and `return false` at the end of the function as a fallback value.

Off-topic for educational purposes (doesn't apply after the suggestion above):

```c
if (!on_lava) {
    return false;
} else {
    return true;
}
```

This snippet is quite low quality. First, since this snippet has both `if` and `else`, and both of the branches are one-liners, there's no need for the negation - it only reduces readability. So let's flip it:

```c
if (on_lava) {
    return true;
} else {
    return false;
}
```

This is still wordy. Both of the branches evaluate to the same statement – `return x`, so we can turn it into a ternary expression. We get:

```c
return on_lava ? true : false;
```

But hopefully you can see that this is silly and can be just represented as:

```c
return on_lava;
```

However, like I said earlier, there's no need to run the entire loop – we can know the state of `on_lava` much earlier. And making the function exit as early as possible is what we call early exits. It's not an optimization technique, it's to boost readability - the `return` statements get highlighted in any decent IDE and you can easily see the control flow.


Don't forget to remove the no longer necessary `on_lava` variable after the fact :)

**Review by rr- — APPROVED** [review]
