### PR TITLE
matrix: add a matrix stack overflow error check and crash message

### LINKED ISSUE #506: Heap corruption in GetRoomBounds
For levels with faulty (discontinued) portals, `GetRoomBounds` can work infinitely, causing `phd_PushMatrix` to exceed the `MAX_MATRICES` limit and write all over the game memory.

The result is a nasty crash.

I think it's the same bug as with #227 . Found with Sabatu's help. Example of a problematic portal:
unknown (1)
unknown

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #506.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Added a matrix stack overflow error check and message if GetRoomBounds runs infinitely.
...

Let me know if this is what you had in mind. Example crash output for #227:
```
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 12
../src/game/draw.c 26 Draw_PrintRoomNumStack Room Number 5
../src/specific/s_shell.c 62 S_Shell_ShowFatalError Push matrix stack overflow.
```

### CODE REVIEW

File: src/game/draw.c [hunk 1]
```diff
@@ -12,10 +12,20 @@
...
 #include "global/vars.h"
+#include "log.h"
 #include "specific/s_misc.h"
 
 static int16_t m_InterpolatedBounds[6] = { 0 };
 static bool m_CameraUnderwater = false;
+static int32_t m_RoomNumStack[MAX_MATRICES + 1] = { 0 };
+static int32_t m_StackIdx = 0;
+
+void Draw_PrintRoomNumStack()
```
Comment (rr-) [inline src/game/draw.c:23]: `(void)`

File: src/game/draw.c [hunk 2]
```diff
@@ -12,10 +12,20 @@
 #include "game/viewport.h"
 #include "global/const.h"
 #include "global/vars.h"
+#include "log.h"
 #include "specific/s_misc.h"
 
 static int16_t m_InterpolatedBounds[6] = { 0 };
 static bool m_CameraUnderwater = false;
+static int32_t m_RoomNumStack[MAX_MATRICES + 1] = { 0 };
+static int32_t m_StackIdx = 0;
```
Comment (rr-) [inline src/game/draw.c:21]: `m_RoomNumStackIdx`

File: src/game/draw.c [hunk 3]
```diff
@@ -12,10 +12,20 @@
 #include "game/viewport.h"
 #include "global/const.h"
 #include "global/vars.h"
+#include "log.h"
 #include "specific/s_misc.h"
 
 static int16_t m_InterpolatedBounds[6] = { 0 };
 static bool m_CameraUnderwater = false;
+static int32_t m_RoomNumStack[MAX_MATRICES + 1] = { 0 };
```
Comment (rr-) [inline src/game/draw.c:20]: This is of a wrong size, should be `MAX_ROOMS_TO_DRAW`.

Rooms are fine, they don't overflow. What's not fine is when the room drawing pushes matrices infinitely because of bad floor data. We display this stack only to help the builders find out the broken room.

File: src/game/draw.c [hunk 4]
```diff
@@ -79,6 +90,7 @@ void GetRoomBounds(int16_t room_num)
         }
     }
     phd_PopMatrix();
+    m_RoomNumStack[m_StackIdx--] = 0;
```
Comment (rr-) [inline src/game/draw.c:93]: I think `m_StackIdx--` alone would suffice, it's not like we'll be trying to read it beyond.
Likewise `phd_PopMatrix` doesn't zero the matrix that was popped from the stack.

File: src/game/draw.h [hunk 5]
```diff
@@ -4,6 +4,7 @@
 
 #include <stdint.h>
 
+void Draw_PrintRoomNumStack();
```
Comment (rr-) [inline src/game/draw.h:7]: `(void)`

File: src/3dsystem/matrix.c [hunk 6]
```diff
@@ -45,12 +47,19 @@ void phd_GenerateW2V(PHD_3DPOS *viewpos)
...
+        Shell_ExitSystem("Push matrix stack overflow.");
+    }
     g_PhdMatrixPtr++;
     g_PhdMatrixPtr[0] = g_PhdMatrixPtr[-1];
 }
 
 void phd_PushUnitMatrix(void)
 {
+    if (g_PhdMatrixPtr + 1 - m_MatrixStack >= MAX_MATRICES) {
+        Shell_ExitSystem("Push unit matrix stack overflow.");
```
Comment (rr-) [inline src/3dsystem/matrix.c:61]: Missing call to `Draw_PrintRoomNumStack`. I don't think the log needs to differentiate between unit matrices and duplicate matrices, IMO not.

**Review by rr- — CHANGES_REQUESTED** [review]
A couple of cosmetic remarks. I like your solution with the room stack, I find it very elegant.

File: src/3dsystem/matrix.c (hunk 6 above)
Comment (rr-) [reply src/3dsystem/matrix.c:62]: I still see the same log message

**Review by rr- — CHANGES_REQUESTED** [review]
Some of the conversations are marked as resolved but I don't see changes. Please push the changes and review them again

File: src/game/draw.c (hunk 2 above)
Comment (rr-) [reply src/game/draw.c:21]: Still the same name

Comment (walkawayy) [reply src/game/draw.c:21]: Oops renamed the wrong thing.

**Review by rr- — APPROVED** [review]
