### PR TITLE
ui: fix default healthbar and airbar behavior

### LINKED ISSUE #266: Bug: Default healthbar and airbar not implemented
Setting `"xbar_showing_mode": "default",` in the JSON doesn't do anything. Instead, `flashing-or-default` behavior is used.

`T1M_BSM_DEFAULT` is missing from `m_BarShowingModes`.

### PR DESCRIPTION
**Pull request by walkawayy**
Closes #266.

### CODE REVIEW

File: src/game/overlay.c [hunk 1]
```diff
@@ -243,18 +244,21 @@ void Overlay_DrawHealthBar()
     int32_t show = g_HealthBarTimer > 0 || hit_points <= 0
         || g_Lara.gun_status == LGS_READY;
     switch (g_Config.healthbar_showing_mode) {
-    case T1M_BSM_ALWAYS:
-        show = 1;
-        break;
-    case T1M_BSM_NEVER:
-        show = 0;
+    case T1M_BSM_DEFAULT:
+        show;
```
Comment (oziphantom) [inline src/game/overlay.c:248]: what is this suppose to be?

File: src/game/overlay.c [hunk 2]
```diff
@@ -268,18 +272,21 @@ void Overlay_DrawAirBar()
     int32_t show = g_Lara.water_status == LWS_UNDERWATER
         || g_Lara.water_status == LWS_SURFACE;
     switch (g_Config.airbar_showing_mode) {
-    case T1M_BSM_ALWAYS:
-        show = 1;
-        break;
-    case T1M_BSM_NEVER:
-        show = 0;
+    case T1M_BSM_DEFAULT:
+        show;
```
Comment (oziphantom) [inline src/game/overlay.c:276]: and this one

**Review by oziphantom — CHANGES_REQUESTED** [review]
at this point should one not also make show a bool since we have it now, as you are changing it anyway.

File: src/game/overlay.c (hunk 1 above)
Comment (walkawayy) [reply src/game/overlay.c:248]: The DEFAULT cases don't need any extra options like the other cases, but I wanted to represent that it is a case.

Comment (oziphantom) [reply src/game/overlay.c:248]: so default doesn't need to modify show. 
which this "does" but also looks like 'somebody forgot to set the default value' at which point you could put a comment to explain, at which you could then just put the comment and not worry about odd "compiler doesn't mind" cases.

Comment (walkawayy) [reply src/game/overlay.c:248]: I’ll just change it to only a break. Idk why I thought to leave show; lol. Late night brain fart.

Comment (walkawayy) [reply src/game/overlay.c:248]: I should just remove that DEFAULT case and make a (C keyword) default case that just breaks.

File: bin/cfg/Tomb1Main.json5 [hunk 3]
```diff
@@ -93,17 +93,17 @@
...
     // Changes how the airbar is displayed. Possible values:
-    // - always: always show the airbar
-    // - default: show the airbar only in the water
-    // - flashing-or-default: show the airbar when Lara's oxygen is 20% or
-    //   below or under normal circumstances
-    // - flashing-only: show the airbar *only* when Lara's oxygen is 20% or /
+    // - default: show the airbar only in the water (as in OG)
+    // - flashing-or-default: flash the airbar when Lara's oxygen is 20% or
+    //   below, or show under normal circumstances
+    // - flashing-only: show and the airbar *only* when Lara's oxygen is 20% or /
```
Comment (rr-) [inline bin/cfg/Tomb1Main.json5:99]: No need for this trailing slash

File: bin/cfg/Tomb1Main.json5 [hunk 4]
```diff
@@ -93,17 +93,17 @@
...
     //   below (useful for challenge runs)
+    // - always: always show the airbar
     // - never: never display the airbar (for challenge runs)
     // In case of airbar, the flashing-or-default mode is there mostly for
     // consistency and the only practical difference is that it's shown when
     // Lara dies. When using the fly cheat, the airbar is never shown.
-    "airbar_showing_mode": "default",
+    "airbar_showing_mode": "flashing-or-default",
```
Comment (rr-) [inline bin/cfg/Tomb1Main.json5:106]: This mode does not make much sense TBH for the airbar. You'll never get a flashing airbar outside of a water body.

File: src/game/overlay.c [hunk 5]
```diff
@@ -172,7 +172,8 @@ static void Overlay_DrawBar(int32_t value, int32_t value_max, int32_t bar_type)
     int32_t blink =
         percent <= blink_threshold && blink_time > blink_interval / 2;
 
-    if (percent && !blink) {
+    if ((percent && !blink)
+        || (g_Config.healthbar_showing_mode == T1M_BSM_DEFAULT)) {
```
Comment (rr-) [inline src/game/overlay.c:176]: Can you describe the rationale of this change?

Comment (walkawayy) [reply src/game/overlay.c:176]: In the PS1 OG game, the bars don’t flash when they are low. This makes it so they don't flash if they are low.

File: bin/cfg/Tomb1Main.json5 (hunk 4 above)
Comment (walkawayy) [reply bin/cfg/Tomb1Main.json5:106]: I didn't add this mode. Just rearranged the order to match the order of the json, enums, and case statement. Want me to remove it?

Comment (rr-) [reply bin/cfg/Tomb1Main.json5:106]: I'm not sure, do you think it makes sense to have it around?
When I added it I only made it to be consistent, but I think that might have been a mistake.

File: src/game/overlay.c (hunk 5 above)
Comment (rr-) [reply src/game/overlay.c:176]: ! That's the thing I needed :)

File: src/game/overlay.c [hunk 6]
```diff
@@ -243,17 +244,19 @@ void Overlay_DrawHealthBar()
...
         break;
     case T1M_BSM_NEVER:
         show = 0;
         break;
-    case T1M_BSM_FLASHING_OR_DEFAULT:
-        show |= hit_points <= (LARA_HITPOINTS * 20) / 100;
-        break;
-    case T1M_BSM_FLASHING_ONLY:
-        show = hit_points <= (LARA_HITPOINTS * 20) / 100;
+    default:
```
Comment (rr-) [inline src/game/overlay.c:259]: This `default: break` idiom is to avoid the compiler complaining about the switch missing certain cases right?

**Review by rr- — APPROVED** [review]

File: src/game/overlay.c (hunk 6 above)
Comment (walkawayy) [reply src/game/overlay.c:259]: I don't think there's a compiler error for no default, but IMO it makes it clear that the default case is just `show` and we didn't forget about it.

File: src/game/overlay.c (hunk 5 above)
Comment (walkawayy) [reply src/game/overlay.c:176]: I just checked. HP bar does flash if health is low, but it does not stay up on the screen.

File: bin/cfg/Tomb1Main.json5 (hunk 4 above)
Comment (walkawayy) [reply bin/cfg/Tomb1Main.json5:106]: I don't see a use for it, but I get your point about consistency. It's not harmful other than lengthening the list of options.

**Review by rr- — CHANGES_REQUESTED** [review]
I tested it and I have two comments:

The healthbar in the default mode should be flashing for consistency with OG, whereas this PR removes it.
Please change the airbar back to `default`. The consequence of `flashing-or-default` is that the game will render empty airbar when Lara dies on the ground (her air is 0), which is a deviation from the OG.

File: src/game/overlay.c (hunk 5 above)
Comment (rr-) [reply src/game/overlay.c:176]: Let's restore this behavior then.

**Comment by walkawayy** [comment]
> 

Ok. I was thinking PS1 behavior was the default. If you see the 5 min mark at this [video](https://www.youtube.com/watch?v=UUNOovpJCho), there's no flashing for air or health bar. TombATI behaves slightly different. If we want the default behavior to flash when low, we should prob change the description. Currently it says:
```
   // - default: show the healthbar at the beginning of a level, after
    //   getting hit or while having weapons equipped (as in OG)
```
While `flashing-or-default` says:
```
   // - flashing-or-default: show the airbar when Lara's oxygen is 20% or
    //   below or under normal circumstances
```

That's why I changed `show` to `flash` on this. I think we just need to clean up the descriptions to more clearly define the behavior we want, then we can implement the code from there once we know exactly what we want.

**Comment by walkawayy** [comment]
@rr- let me know what you prefer for default behavior on this. I'll update the description and behavior to match.

**Comment by rr-** [comment]
I would like to keep compatibility with TombATI with `default` (possibly rename it to something else) and if we want to have compatibility with PS1, introduce a separate mode for it, e.g. not have the flashing part removed.

By default I would like to have the healthbar shown when Lara's health changes, or if it's under 20% in which case I'd like it to flash. This is `flashing-or-default`. I would like to have the airbar shown when she's underwater or on the water surface, which is `default`. (`default-or-flashing` doesn't make sense here as the only difference is that it will only be shown when Lara's dead on the ground, which looks like a bug. I'm OK with removing this mode altogether for the airbar.)

**Comment by walkawayy** [comment]
How ugly is... Healthbar:
```
// Changes how the healthbar is displayed. Possible values:
// - default: show the healthbar at the start of a level, after getting
//   hit, or while having weapons equipped; flash the healthbar if it's already
//   on screen when Lara's health is 20% or below (TombATI)
// - flashing-or-default: constantly flash the healthbar when Lara's
//   health is 20% or below, or show under default circumstances
// - flashing-only: show the healthbar *only* when Lara's health is 20% or
//   below (useful for challenge runs)
// - always: always show the healthbar
// - never: never display the healthbar (for challenge runs)
// - psx: show the healthbar under default circumstances with no flashing
"healthbar_showing_mode": "flashing-or-default",
```

It's just slightly different for airbar because `flashing-or-default` would be `default` for air. Maybe:
```
// Changes how the airbar is displayed. Possible values:
// - default: show the airbar only in the water and flash the airbar when
//   Lara's oxygen is 20% or below (TombATI)
// - flashing-only: show the airbar *only* when Lara's oxygen is 20% or
//   below (for challenge runs)
// - never: never display the airbar (for challenge runs)
// - psx: show the healthbar under default circumstances with no flashing
```

**Comment by rr-** [comment]
Looks good to me. I like that we don't break backwards compatibility with this.

**Comment by walkawayy** [comment]
Lol idk I use PS1 and PSX. The reasoning is the console was code named PlayStation X. The gaming media called it PSX, and even though the X was dropped the name stuck. There was also no PS2 yet, so it wasn't called PS1 until PS2 started coming out. Let's just call it PS1 since that's clearer.


I also want to consider moving the blink code:
```
    const int32_t blink_interval = 20;
    const int32_t blink_threshold = bar_type == BT_ENEMY_HEALTH ? 0 : 20;
    int32_t blink_time = blink_counter++ % blink_interval;
    int32_t blink =
        percent <= blink_threshold && blink_time > blink_interval / 2;
```
to `Overlay_DrawHealthBar` and `Overlay_DrawAirBar` and calculate it in the case statements. Then pass blink as a param to `Overlay_DrawBar`. Any thoughts?

Also what is the difference between:
```
    case T1M_BSM_FLASHING_ONLY:
        show = g_Lara.air <= (LARA_AIR * 20) / 100;
        break;

    if (!show) {
        return;
    }
```
and `if ((percent && !blink)`? Does the `show` in the case statements cause the entire healthbar (including the border) to flash while the `blink` causes only the inner red color to flash?

**Comment by rr-** [comment]
>Moving the code

OK so long as the new code guarantees us to have this:



and not this:

**Comment by rr-** [comment]
Also to reduce amount of module-level variables consider wrapping the bits for each bar in its own struct.
Also consider moving `g_HealthBarTimer` to a module-level constant and add setter functions for use in other modules (`Overlay_SetHealtBarTimer`, `Overlay_TimerTick` or something like that).

File: src/game/overlay.c [hunk 7]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+}
+
 static void Overlay_GetBarLocation(
     int8_t bar_location, int32_t width, int32_t height, int32_t *x, int32_t *y);
-static void Overlay_DrawBar(int32_t value, int32_t value_max, int32_t bar_type);
+static void Overlay_DrawBar(BAR_INFO *draw_bar);
 static void Overlay_OnAmmoTextRemoval(const TEXTSTRING *textstring);
 static void Overlay_OnFPSTextRemoval(const TEXTSTRING *textstring);
 
+static void Overlay_GetBlink(BAR_INFO *blink_bar)
```
Comment (walkawayy) [inline src/game/overlay.c:143]: Should I make the function bars (like `blink_bar`) all the same name since they are passed as pointers? I never know what people prefer to name as far as different function but same variables go.

File: src/game/overlay.c [hunk 8]
```diff
@@ -12,6 +12,8 @@
 
 #include <stdio.h>
 
+#include "log.h"
```
Comment (rr-) [inline src/game/overlay.c:15]: I don't think we need this include, and if we do, it should be put with the rest of the `""` includes.

File: src/game/overlay.c [hunk 9]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    m_HealthBar.max_value = LARA_HITPOINTS;
+    m_HealthBar.show_mode = g_Config.healthbar_showing_mode;
+    m_HealthBar.show = 0;
+    m_HealthBar.blink = 0;
+    m_HealthBar.timer = 40;
+    m_HealthBar.color = g_Config.healthbar_color;
+    m_HealthBar.bar_location = g_Config.healthbar_location;
+}
+
+static BAR_INFO m_AirBar = { 0 };
```
Comment (rr-) [inline src/game/overlay.c:109]: Let's lump all static variables together, then all static functions, then all public functions.
Also all functions should have a forward declaration (I know they may not be needed, but this is for consistency so that we don't have to think about it.)

File: src/game/overlay.c (hunk 7 above)
Comment (rr-) [reply src/game/overlay.c:143]: Let's just name it `bar` or `bar_info` across all functions :)

File: src/game/overlay.c [hunk 10]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
 static void Overlay_OnAmmoTextRemoval(const TEXTSTRING *textstring);
 static void Overlay_OnFPSTextRemoval(const TEXTSTRING *textstring);
 
+static void Overlay_GetBlink(BAR_INFO *blink_bar)
+{
+    if (blink_bar->show_mode == T1M_BSM_PS1) {
+        blink_bar->blink = 0;
+    }
+
+    static int32_t blink_counter = 0;
```
Comment (rr-) [inline src/game/overlay.c:149]: I think we can move this to `BAR_INFO`.

File: src/game/overlay.c [hunk 11]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    const int32_t percent_max = 100;
+
+    if (blink_bar->value < 0) {
+        blink_bar->value = 0;
+    } else if (blink_bar->value > blink_bar->max_value) {
+        blink_bar->value = blink_bar->max_value;
+    }
```
Comment (rr-) [inline src/game/overlay.c:156]: I think we can use `CLAMP` macro here.

File: src/game/overlay.c [hunk 12]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
 static void Overlay_OnFPSTextRemoval(const TEXTSTRING *textstring);
 
+static void Overlay_GetBlink(BAR_INFO *blink_bar)
+{
+    if (blink_bar->show_mode == T1M_BSM_PS1) {
+        blink_bar->blink = 0;
+    }
+
+    static int32_t blink_counter = 0;
+    const int32_t percent_max = 100;
```
Comment (rr-) [inline src/game/overlay.c:150]: I'm not sure if it makes sense to keep it as a variable, below we're using `* 100` as a literal numeral.

File: src/game/overlay.c [hunk 13]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
-static void Overlay_DrawBar(int32_t value, int32_t value_max, int32_t bar_type);
+static void Overlay_DrawBar(BAR_INFO *draw_bar);
 static void Overlay_OnAmmoTextRemoval(const TEXTSTRING *textstring);
 static void Overlay_OnFPSTextRemoval(const TEXTSTRING *textstring);
 
+static void Overlay_GetBlink(BAR_INFO *blink_bar)
+{
+    if (blink_bar->show_mode == T1M_BSM_PS1) {
+        blink_bar->blink = 0;
+    }
```
Comment (rr-) [inline src/game/overlay.c:147]: I think we're missing `return;` here to skip triggering the rest of the blink calculations.

File: src/game/overlay.c [hunk 14]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+
+    if (blink_bar->value < 0) {
+        blink_bar->value = 0;
+    } else if (blink_bar->value > blink_bar->max_value) {
+        blink_bar->value = blink_bar->max_value;
+    }
+    int32_t percent = blink_bar->value * 100 / blink_bar->max_value;
+
+    const int32_t blink_interval = 20;
+    const int32_t blink_threshold = blink_bar->type == BT_ENEMY_HEALTH ? 0 : 20;
```
Comment (rr-) [inline src/game/overlay.c:160]: TBH I'd move this check (for the enemy healthbar) to the beginning of the function and make a similar early exit.

File: src/game/overlay.c [hunk 15]
```diff
@@ -113,40 +193,27 @@ static void Overlay_GetBarLocation(
...
-        value = 0;
-    } else if (value > value_max) {
-        value = value_max;
+    if (draw_bar->value < 0) {
+        draw_bar->value = 0;
+    } else if (draw_bar->value > draw_bar->max_value) {
+        draw_bar->value = draw_bar->max_value;
     }
-    int32_t percent = value * 100 / value_max;
+    int32_t percent = draw_bar->value * 100 / draw_bar->max_value;
```
Comment (rr-) [inline src/game/overlay.c:205]: We can use `CLAMP` value. Also since we duplicate the code from above, maybe it's good to introduce a function for this `Overlay_BarGetPercent(BAR_INFO *bar)`

File: src/game/overlay.c [hunk 16]
```diff
@@ -113,40 +193,27 @@ static void Overlay_GetBarLocation(
...
-        bar_color = g_Config.healthbar_color;
-    } else if (bar_type == BT_LARA_AIR) {
-        Overlay_GetBarLocation(g_Config.airbar_location, width, height, &x, &y);
-        bar_color = g_Config.airbar_color;
-    } else if (bar_type == BT_ENEMY_HEALTH) {
-        Overlay_GetBarLocation(
-            g_Config.enemy_healthbar_location, width, height, &x, &y);
-        bar_color = g_Config.enemy_healthbar_color;
-    }
+    Overlay_GetBarLocation(draw_bar->bar_location, width, height, &x, &y);
```
Comment (rr-) [inline src/game/overlay.c:216]: Consider making `Bar` a common prefix across all bar functions i.e. `Overlay_BarGetLocation` etc. to lump those functions together.

File: src/game/overlay.c [hunk 17]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
+void Overlay_SetHealtBarTimer(int16_t health_bar_timer)
+{
+    m_HealthBar.timer = health_bar_timer;
+}
+
+void Overlay_TimerTick()
+{
+    m_HealthBar.timer--;
+    if (m_HealthBar.timer < 0) {
+        Overlay_SetHealtBarTimer(0);
```
Comment (rr-) [inline src/game/overlay.c:296]: I think we can use one of the variants of the `CLAMP` function here.

File: src/game/overlay.c [hunk 18]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
+    }
 }
 
 void Overlay_DrawHealthBar()
 {
     static int32_t old_hit_points = 0;
 
-    for (int i = 0; i < 6; i++) {
+    for (int32_t i = 0; i < 6; i++) {
```
Comment (rr-) [inline src/game/overlay.c:304]: Let's leave it as `int` IMO, although no strong feeling about this

File: src/game/overlay.c [hunk 19]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
-    int hit_points = g_LaraItem->hit_points;
-    if (hit_points < 0) {
-        hit_points = 0;
-    } else if (hit_points > LARA_HITPOINTS) {
-        hit_points = LARA_HITPOINTS;
+    m_HealthBar.value = g_LaraItem->hit_points;
+    if (m_HealthBar.value < 0) {
+        m_HealthBar.value = 0;
+    } else if (m_HealthBar.value > m_HealthBar.max_value) {
+        m_HealthBar.value = m_HealthBar.max_value;
```
Comment (rr-) [inline src/game/overlay.c:312]: We can use `CLAMP` for this

File: src/game/overlay.c [hunk 20]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
     }
 
-    if (old_hit_points != hit_points) {
-        old_hit_points = hit_points;
-        g_HealthBarTimer = 40;
+    if (old_hit_points != m_HealthBar.value) {
+        old_hit_points = m_HealthBar.value;
+        Overlay_SetHealtBarTimer(40);
```
Comment (rr-) [inline src/game/overlay.c:317]: I think it's OK to just use `m_HealthBar.timer` directly here, since it's just a simple assignment, but no strong feelings about it.

File: src/game/overlay.c [hunk 21]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
         || g_Lara.gun_status == LGS_READY;
-    switch (g_Config.healthbar_showing_mode) {
+    switch (m_HealthBar.show_mode) {
+    case T1M_BSM_FLASHING_OR_DEFAULT:
+        m_HealthBar.show |=
+            m_HealthBar.value <= (m_HealthBar.max_value * 20) / 100;
+        break;
+    case T1M_BSM_FLASHING_ONLY:
+        m_HealthBar.show =
+            m_HealthBar.value <= (m_HealthBar.max_value * 20) / 100;
```
Comment (rr-) [inline src/game/overlay.c:329]: I think `20` should be moved as a module-level constant for all usages. A name such as `BLINK_THRESHOLD`.

File: src/game/overlay.c [hunk 22]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
       { 120, 60, 70 } },
 };
 
+typedef struct BAR_INFO {
+    int32_t type;
```
Comment (rr-) [inline src/game/overlay.c:84]: Consider making it a `BAR_TYPE`

File: src/game/overlay.c [hunk 23]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    int32_t value;
+    int32_t max_value;
+    int32_t show;
+    int32_t show_mode;
```
Comment (rr-) [inline src/game/overlay.c:88]: Consider making this a `T1M_BAR_SHOW_MODE`

File: src/game/overlay.c [hunk 24]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    int32_t blink;
```
Comment (rr-) [inline src/game/overlay.c:89]: Consider making it a `bool`

File: src/game/overlay.c [hunk 25]
```diff
@@ -78,12 +80,90 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    int32_t timer;
+    int32_t color;
+    int32_t bar_location;
```
Comment (rr-) [inline src/game/overlay.c:92]: Consider making it a `T1M_BAR_LOCATION`

File: src/game/overlay.c [hunk 26]
```diff
@@ -214,98 +278,114 @@ void Overlay_Init()
...
 
 void Overlay_DrawAirBar()
 {
-    int32_t show = g_Lara.water_status == LWS_UNDERWATER
+    m_AirBar.value = g_Lara.air;
+    if (m_AirBar.value < 0) {
+        m_AirBar.value = 0;
+    } else if (g_Lara.air > m_AirBar.max_value) {
+        m_AirBar.value = m_AirBar.max_value;
+    }
```
Comment (rr-) [inline src/game/overlay.c:354]: We can use `CLAMP`

File: src/game/overlay.h [hunk 27]
```diff
@@ -4,6 +4,8 @@
 
 void Overlay_Init();
 
+void Overlay_SetHealtBarTimer(int16_t health_bar_timer);
```
Comment (rr-) [inline src/game/overlay.h:7]: Just `timer` will do

File: src/game/setup.c [hunk 28]
```diff
@@ -119,7 +119,7 @@ int32_t InitialiseLevel(int32_t level_num, GAMEFLOW_LEVEL_TYPE level_type)
 
     Overlay_Init();
 
-    g_HealthBarTimer = 100;
+    Overlay_SetHealtBarTimer(100); // TODO Move this to Overlay_Init()?
```
Comment (rr-) [inline src/game/setup.c:122]: Not sure. On one hand this is a good decision, on another here we're very explicit about flashing the health for 100 frames(?) at the start of the level. IMO let's leave it as-is, maybe move the blank line above under this line to lump `Overlay_` calls together.

**Review by rr- — CHANGES_REQUESTED** [review]
Great changes, I have only cosmetic comments.

File: src/game/overlay.c (hunk 10 above)
Comment (walkawayy) [reply src/game/overlay.c:149]: Honestly I don't understand the point of `blink_counter`. It's only used in one line:
`    int32_t blink_time = blink_counter++ % blink_interval;`

Isn't it always just going to be `1 % blink_interval`?

Comment (walkawayy) [reply src/game/overlay.c:149]: Also went with `bar_info` for easier differentiation when searching and reading the code IMO.

File: src/game/overlay.c (hunk 14 above)
Comment (walkawayy) [reply src/game/overlay.c:160]: Enemy health bars should never blink? I was considering making it behave the same as the user health bar setting. But it probably doesn't make sens e to do that. I also need to make the blink threshold a constant.

File: src/game/overlay.c (hunk 18 above)
Comment (walkawayy) [reply src/game/overlay.c:304]: Ok. I changed it since most of the ints are given defined types and it seemed inconsistent. But it shouldn't matter for a loop counter.

File: src/game/overlay.c (hunk 20 above)
Comment (walkawayy) [reply src/game/overlay.c:317]: I wasn't sure for this either. I decided to use the function because every other time it's set uses that. But local in the function it could be the simple assignment since that's how the rest of it is set I guess.

File: src/game/overlay.c (hunk 22 above)
Comment (walkawayy) [reply src/game/overlay.c:84]: I originally had it as that, but then it became `m_HealthBar.bar_type` which seemed like unneeded characters.

File: src/game/overlay.c (hunk 23 above)
Comment (walkawayy) [reply src/game/overlay.c:88]: Didn't even realize / think to do that lol. Mind blown.

File: src/game/overlay.c (hunk 10 above)
Comment (rr-) [reply src/game/overlay.c:149]: It's not a bad practice.

Because `blink_counter` is declared as static, it behaves like a module-level variable. So it'll be 1, 2, 3, … MAX_INT, 0, 1,   etc. Declaring static variables in function bodies is a bad practice, because it introduces global state in a stealthy way. Hence my proposal to move it to `BAR_INFO`.

**Comment by walkawayy** [comment]
I think I addressed all of the review comments. Tried to list them all in the commit message.

File: bin/cfg/Tomb1Main.json5 [hunk 29]
```diff
@@ -61,15 +61,17 @@
...
+    // - flashing-or-default: constantly flash the healthbar when Lara's
+    //   health is 20% or below, or show under default circumstances
     // - flashing-only: show the healthbar *only* when Lara's health is 20% or
-    //   below (useful for challenge runs)
+    //   below (for challenge runs)
+    // - always: always show the healthbar
     // - never: never display the healthbar (for challenge runs)
-    "healthbar_showing_mode": "flashing-or-default",
+    // - ps1: show the healthbar under default circumstances with no flashing
+    "healthbar_showing_mode": "default",
```
Comment (rr-) [inline bin/cfg/Tomb1Main.json5:74]: I think we agreed to keep it as `flashing-or-default`; from yesterday's comment:
>By default I would like to have the healthbar shown when Lara's health changes, or if it's under 20% in which case I'd like it to flash. This is `flashing-or-default`

File: src/game/overlay.c [hunk 30]
```diff
@@ -78,14 +79,105 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    int32_t value;
+    int32_t max_value;
+    int32_t percent;
+    bool show;
+    T1M_BAR_SHOW_MODE show_mode;
+    bool blink;
+    int32_t blink_counter;
+    int32_t timer;
+    int32_t color;
+    T1M_BAR_LOCATION bar_location;
```
Comment (rr-) [inline src/game/overlay.c:93]: IMO we can drop `T1M_` prefix from these enums, and simplify `bar_location` to `location`

File: src/game/overlay.c [hunk 31]
```diff
@@ -78,14 +79,105 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
 };
 
-static void Overlay_GetBarLocation(
-    int8_t bar_location, int32_t width, int32_t height, int32_t *x, int32_t *y);
-static void Overlay_DrawBar(int32_t value, int32_t value_max, int32_t bar_type);
+typedef struct BAR_INFO {
+    BAR_TYPE type;
+    int32_t value;
+    int32_t max_value;
+    int32_t percent;
```
Comment (rr-) [inline src/game/overlay.c:86]: `percent` duplicates what can be calculated from `value` and `max_value`, I'd rather we'd store only one source of truth – in the current form it is unclear which is more valid during calculations.

File: src/game/overlay.c [hunk 32]
```diff
@@ -78,14 +79,105 @@ static RGB888 m_ColorBarMap[][COLOR_STEPS] = {
...
+    m_EnemyBar.blink = false;
+    m_EnemyBar.blink_counter = 0;
+    m_EnemyBar.timer = 0;
+    m_EnemyBar.color = g_Config.enemy_healthbar_color;
+    m_EnemyBar.bar_location = g_Config.enemy_healthbar_location;
+}
+
+static void Overlay_BarGetPercent(BAR_INFO *bar_info)
+{
+    bar_info->percent = bar_info->value * 100 / bar_info->max_value;
```
Comment (rr-) [inline src/game/overlay.c:159]: To continue my earlier comment – here I'd prefer for us to just return the calculated value instead of store it in the `BAR_INFO`.

File: src/game/overlay.c [hunk 33]
```diff
@@ -113,40 +205,20 @@ static void Overlay_GetBarLocation(
...
-    static int32_t blink_counter = 0;
-    const int32_t percent_max = 100;
-
-    if (value < 0) {
-        value = 0;
-    } else if (value > value_max) {
-        value = value_max;
-    }
-    int32_t percent = value * 100 / value_max;
+    int32_t percent = bar_info->value * 100 / bar_info->max_value;
```
Comment (rr-) [inline src/game/overlay.c:210]: Here we could use `int32_t percent = Overlay_BarGetPercent(bar_info);`

**Review by rr- — COMMENTED** [review]
Almost there :)

File: bin/cfg/Tomb1Main.json5 (hunk 29 above)
Comment (walkawayy) [reply bin/cfg/Tomb1Main.json5:74]: Ya sorry. Changed it to TombATI and forgot to change it back.

**Review by rr- — COMMENTED** [review]
I didn't notice one more change in the config

**Comment by walkawayy** [comment]
> I didn't notice one more change in the config – by changing the default bar location we lose compatibility with OG TombATI, TR2 and TR3; possibly more games.

Ah sorry again. I keep mixing up my windows with the config for my game folder and my dev folder. Happens because I use a script to copy everything out of WSL.

**Review by rr- — APPROVED** [review]
LGTM.
